
export const PRODUCTS = [
  {
    id: 'm1',
    name: 'Classic Linen Shirt',
    price: 89.99,
    category: 'Men',
    category2: 'Clothing',
    category3: 'Shirts',
    category4: 'Linen',
    variant: 'Optic White',
    brand: 'Prateek Gharat',
    businessVertical: 'retail',
    description: 'Breathable linen shirt perfect for summer evenings and professional settings. Crafted from 100% European flax.',
    image: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&q=80&w=800',
    rating: 4.5,
    reviews: 124
  },
  {
    id: 'w1',
    name: 'Floral Summer Dress',
    price: 129.50,
    category: 'Women',
    category2: 'Clothing',
    category3: 'Dresses',
    category4: 'Midi',
    variant: 'Rose Garden Print',
    brand: 'Prateek Gharat',
    businessVertical: 'retail',
    description: 'Elegant floral patterns on a lightweight silk blend fabric. Features a delicate waist tie and flowy hem.',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    reviews: 89
  },
  {
    id: 'k1',
    name: 'Cotton Play Set',
    price: 45.00,
    category: 'Kids',
    category2: 'Clothing',
    category3: 'Sets',
    category4: 'Active',
    variant: 'Sky Blue',
    brand: 'Prateek Gharat',
    businessVertical: 'retail',
    description: 'Durable and soft organic cotton set for active toddlers. Hypoallergenic and easy to wash.',
    image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    reviews: 56
  },
  {
    id: 'a1',
    name: 'Minimalist Leather Watch',
    price: 199.00,
    category: 'Accessories',
    category2: 'Watches',
    category3: 'Analogue',
    category4: 'Leather Strap',
    variant: 'Mocha / Silver',
    brand: 'Prateek Gharat',
    businessVertical: 'retail',
    description: 'Handcrafted leather strap with a timeless stainless steel case. Water resistant up to 50m.',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    reviews: 210
  },
  {
    id: 'm2',
    name: 'Urban Cargo Pants',
    price: 75.00,
    category: 'Men',
    category2: 'Clothing',
    category3: 'Trousers',
    category4: 'Cargo',
    variant: 'Olive Drab',
    brand: 'Prateek Gharat',
    businessVertical: 'retail',
    description: 'Functional style for the modern city dweller. Multiple utility pockets and reinforced stitching.',
    image: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&q=80&w=800',
    rating: 4.3,
    reviews: 45
  },
  {
    id: 'w2',
    name: 'Evening Satin Gown',
    price: 249.00,
    category: 'Women',
    category2: 'Clothing',
    category3: 'Dresses',
    category4: 'Evening',
    variant: 'Emerald Green',
    brand: 'Prateek Gharat',
    businessVertical: 'retail',
    description: 'Turn heads in this deep emerald green satin gown. Floor length with a graceful side slit.',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    reviews: 32
  }
];
